# Generated by Django 4.0.3 on 2022-05-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
