# Generated by Django 4.0.3 on 2022-05-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_song_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
